/**
 * Shared types for workflow steps and pipelines.
 * These types ensure consistency across all workflow operations.
 */

/**
 * Standard result type for workflow steps.
 * All steps should return either success with data or error with message.
 */
export interface StepResult<T = unknown> {
  success: boolean;
  data?: T;
  error?: string;
}

/**
 * Report types generated by Letta agents.
 */
export type LettaReportType =
  | "compliance"
  | "duplicates"
  | "editorial"
  | "metadata";

/**
 * Parsed agent response structure.
 */
export interface ParsedAgentResponse {
  content: string;
  metadata: Record<string, unknown>;
  status: "complete" | "incomplete";
  rawResponse?: string;
}

/**
 * Publication target platforms.
 */
// Today
export type PublicationPlatform = "refugies.info";
// Future
// export type PublicationPlatform = "refugies.info" | "etrangers.info" | "other";

/**
 * Data source types for ingestion.
 */
export type IngestionSource = "rco" | "di";
