-- Seed letta_reports — scénarios crafted (RI-1243)
-- Pas de rapports Letta dans le seed crafté.
-- Les compliance_status sont définis directement sur ingestion_records.
-- Les rapports seront générés au fil des tests manuels.
