// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  AsDictListApiV0DocFraisGetData,
  AsDictListApiV0DocFraisGetResponses,
  AsDictListApiV0DocLabelsNationauxGetData,
  AsDictListApiV0DocLabelsNationauxGetResponses,
  AsDictListApiV0DocModesAccueilGetData,
  AsDictListApiV0DocModesAccueilGetResponses,
  AsDictListApiV0DocModesOrientationAccompagnateurGetData,
  AsDictListApiV0DocModesOrientationAccompagnateurGetResponses,
  AsDictListApiV0DocModesOrientationBeneficiaireGetData,
  AsDictListApiV0DocModesOrientationBeneficiaireGetResponses,
  AsDictListApiV0DocProfilsGetData,
  AsDictListApiV0DocProfilsGetResponses,
  AsDictListApiV0DocThematiquesGetData,
  AsDictListApiV0DocThematiquesGetResponses,
  AsDictListApiV0DocTypologiesServicesGetData,
  AsDictListApiV0DocTypologiesServicesGetResponses,
  AsDictListApiV0DocTypologiesStructuresGetData,
  AsDictListApiV0DocTypologiesStructuresGetResponses,
  AsDictListApiV1DocFraisGetData,
  AsDictListApiV1DocFraisGetResponses,
  AsDictListApiV1DocModesAccueilGetData,
  AsDictListApiV1DocModesAccueilGetResponses,
  AsDictListApiV1DocModesMobilisationGetData,
  AsDictListApiV1DocModesMobilisationGetResponses,
  AsDictListApiV1DocPersonnesMobilisatricesGetData,
  AsDictListApiV1DocPersonnesMobilisatricesGetResponses,
  AsDictListApiV1DocPublicsGetData,
  AsDictListApiV1DocPublicsGetResponses,
  AsDictListApiV1DocReseauxPorteursGetData,
  AsDictListApiV1DocReseauxPorteursGetResponses,
  AsDictListApiV1DocThematiquesGetData,
  AsDictListApiV1DocThematiquesGetResponses,
  AsDictListApiV1DocTypesServicesGetData,
  AsDictListApiV1DocTypesServicesGetResponses,
  ListServicesEndpointApiV0ServicesGetData,
  ListServicesEndpointApiV0ServicesGetErrors,
  ListServicesEndpointApiV0ServicesGetResponses,
  ListServicesEndpointApiV1ServicesGetData,
  ListServicesEndpointApiV1ServicesGetErrors,
  ListServicesEndpointApiV1ServicesGetResponses,
  ListSourcesEndpointApiV0SourcesGetData,
  ListSourcesEndpointApiV0SourcesGetResponses,
  ListSourcesEndpointApiV1SourcesGetData,
  ListSourcesEndpointApiV1SourcesGetResponses,
  ListStructuresEndpointApiV0StructuresGetData,
  ListStructuresEndpointApiV0StructuresGetErrors,
  ListStructuresEndpointApiV0StructuresGetResponses,
  ListStructuresEndpointApiV1StructuresGetData,
  ListStructuresEndpointApiV1StructuresGetErrors,
  ListStructuresEndpointApiV1StructuresGetResponses,
  RetrieveServiceEndpointApiV0ServicesSourceIdGetData,
  RetrieveServiceEndpointApiV0ServicesSourceIdGetErrors,
  RetrieveServiceEndpointApiV0ServicesSourceIdGetResponses,
  RetrieveServiceEndpointApiV1ServicesIdGetData,
  RetrieveServiceEndpointApiV1ServicesIdGetErrors,
  RetrieveServiceEndpointApiV1ServicesIdGetResponses,
  RetrieveStructureEndpointApiV0StructuresSourceIdGetData,
  RetrieveStructureEndpointApiV0StructuresSourceIdGetErrors,
  RetrieveStructureEndpointApiV0StructuresSourceIdGetResponses,
  RetrieveStructureEndpointApiV1StructuresIdGetData,
  RetrieveStructureEndpointApiV1StructuresIdGetErrors,
  RetrieveStructureEndpointApiV1StructuresIdGetResponses,
  SearchServicesEndpointApiV0SearchServicesGetData,
  SearchServicesEndpointApiV0SearchServicesGetErrors,
  SearchServicesEndpointApiV0SearchServicesGetResponses,
  SearchServicesEndpointApiV1SearchServicesGetData,
  SearchServicesEndpointApiV1SearchServicesGetErrors,
  SearchServicesEndpointApiV1SearchServicesGetResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Lister les structures consolidées
 */
export const listStructuresEndpointApiV1StructuresGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListStructuresEndpointApiV1StructuresGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ListStructuresEndpointApiV1StructuresGetResponses,
    ListStructuresEndpointApiV1StructuresGetErrors,
    ThrowOnError
  >({ url: "/api/v1/structures", ...options });

/**
 * Détailler une structure
 */
export const retrieveStructureEndpointApiV1StructuresIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    RetrieveStructureEndpointApiV1StructuresIdGetData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).get<
    RetrieveStructureEndpointApiV1StructuresIdGetResponses,
    RetrieveStructureEndpointApiV1StructuresIdGetErrors,
    ThrowOnError
  >({ url: "/api/v1/structures/{id}", ...options });

/**
 * Lister les sources consolidées
 */
export const listSourcesEndpointApiV1SourcesGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListSourcesEndpointApiV1SourcesGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ListSourcesEndpointApiV1SourcesGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/v1/sources", ...options });

/**
 * Lister les services consolidés
 */
export const listServicesEndpointApiV1ServicesGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListServicesEndpointApiV1ServicesGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ListServicesEndpointApiV1ServicesGetResponses,
    ListServicesEndpointApiV1ServicesGetErrors,
    ThrowOnError
  >({ url: "/api/v1/services", ...options });

/**
 * Détailler un service
 */
export const retrieveServiceEndpointApiV1ServicesIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<RetrieveServiceEndpointApiV1ServicesIdGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    RetrieveServiceEndpointApiV1ServicesIdGetResponses,
    RetrieveServiceEndpointApiV1ServicesIdGetErrors,
    ThrowOnError
  >({ url: "/api/v1/services/{id}", ...options });

/**
 * Rechercher des services
 *
 * ## Rechercher des services
 *
 * La recherche de services permet de trouver des services dans une commune et à
 * proximité.
 *
 * Les services peuvent être filtrés selon par thématiques, frais, typologies et
 * code_insee de commune.
 *
 * En particulier, lorsqu'un `code_commune` est fourni :
 *
 * * les services sont filtrés par zone de diffusion lorsque celle-ci est définie.
 * * de plus, les services en présentiel sont filtrés dans un rayon de 50km autour de
 * la commune ou du point de recherche fourni.
 * * le champ `distance` est :
 * * rempli pour les services (non exclusivement) en présentiel.
 * * laissé vide pour les services à distance et par défaut si le mode d'accueil
 * n'est pas définie.
 * * les résultats sont triés par distance croissante.
 */
export const searchServicesEndpointApiV1SearchServicesGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    SearchServicesEndpointApiV1SearchServicesGetData,
    ThrowOnError
  >,
) =>
  (options?.client ?? client).get<
    SearchServicesEndpointApiV1SearchServicesGetResponses,
    SearchServicesEndpointApiV1SearchServicesGetErrors,
    ThrowOnError
  >({ url: "/api/v1/search/services", ...options });

/**
 * Récupérer le référentiel des frais
 */
export const asDictListApiV1DocFraisGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AsDictListApiV1DocFraisGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    AsDictListApiV1DocFraisGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/v1/doc/frais", ...options });

/**
 * Récupérer le référentiel des modes d'accueil
 */
export const asDictListApiV1DocModesAccueilGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AsDictListApiV1DocModesAccueilGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    AsDictListApiV1DocModesAccueilGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/v1/doc/modes-accueil", ...options });

/**
 * Récupérer le référentiel des modes de mobilisation
 */
export const asDictListApiV1DocModesMobilisationGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AsDictListApiV1DocModesMobilisationGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    AsDictListApiV1DocModesMobilisationGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/v1/doc/modes-mobilisation", ...options });

/**
 * Récupérer le référentiel des personnes mobilisatrices
 */
export const asDictListApiV1DocPersonnesMobilisatricesGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    AsDictListApiV1DocPersonnesMobilisatricesGetData,
    ThrowOnError
  >,
) =>
  (options?.client ?? client).get<
    AsDictListApiV1DocPersonnesMobilisatricesGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/v1/doc/personnes-mobilisatrices", ...options });

/**
 * Récupérer le référentiel des publics
 */
export const asDictListApiV1DocPublicsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AsDictListApiV1DocPublicsGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    AsDictListApiV1DocPublicsGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/v1/doc/publics", ...options });

/**
 * Récupérer le référentiel des réseaux porteurs
 */
export const asDictListApiV1DocReseauxPorteursGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AsDictListApiV1DocReseauxPorteursGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    AsDictListApiV1DocReseauxPorteursGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/v1/doc/reseaux-porteurs", ...options });

/**
 * Récupérer le référentiel des thématiques
 */
export const asDictListApiV1DocThematiquesGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AsDictListApiV1DocThematiquesGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    AsDictListApiV1DocThematiquesGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/v1/doc/thematiques", ...options });

/**
 * Récupérer le référentiel des types de services
 */
export const asDictListApiV1DocTypesServicesGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AsDictListApiV1DocTypesServicesGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    AsDictListApiV1DocTypesServicesGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/v1/doc/types-services", ...options });

/**
 * Lister les structures consolidées
 *
 * @deprecated
 */
export const listStructuresEndpointApiV0StructuresGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListStructuresEndpointApiV0StructuresGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ListStructuresEndpointApiV0StructuresGetResponses,
    ListStructuresEndpointApiV0StructuresGetErrors,
    ThrowOnError
  >({ url: "/api/v0/structures", ...options });

/**
 * Détailler une structure
 *
 * @deprecated
 */
export const retrieveStructureEndpointApiV0StructuresSourceIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    RetrieveStructureEndpointApiV0StructuresSourceIdGetData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).get<
    RetrieveStructureEndpointApiV0StructuresSourceIdGetResponses,
    RetrieveStructureEndpointApiV0StructuresSourceIdGetErrors,
    ThrowOnError
  >({ url: "/api/v0/structures/{source}/{id}", ...options });

/**
 * Lister les sources consolidées
 *
 * @deprecated
 */
export const listSourcesEndpointApiV0SourcesGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListSourcesEndpointApiV0SourcesGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ListSourcesEndpointApiV0SourcesGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/v0/sources", ...options });

/**
 * Lister les services consolidés
 *
 * @deprecated
 */
export const listServicesEndpointApiV0ServicesGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListServicesEndpointApiV0ServicesGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ListServicesEndpointApiV0ServicesGetResponses,
    ListServicesEndpointApiV0ServicesGetErrors,
    ThrowOnError
  >({ url: "/api/v0/services", ...options });

/**
 * Détailler un service
 *
 * @deprecated
 */
export const retrieveServiceEndpointApiV0ServicesSourceIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    RetrieveServiceEndpointApiV0ServicesSourceIdGetData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).get<
    RetrieveServiceEndpointApiV0ServicesSourceIdGetResponses,
    RetrieveServiceEndpointApiV0ServicesSourceIdGetErrors,
    ThrowOnError
  >({ url: "/api/v0/services/{source}/{id}", ...options });

/**
 * Rechercher des services
 *
 * ## Rechercher des services
 *
 * La recherche de services permet de trouver des services dans une commune et à
 * proximité.
 *
 * Les services peuvent être filtrés selon par thématiques, frais, typologies et
 * code_insee de commune.
 *
 * En particulier, lorsqu'un `code_commune` est fourni :
 *
 * * les services sont filtrés par zone de diffusion lorsque celle-ci est définie.
 * * de plus, les services en présentiel sont filtrés dans un rayon de 50km autour de
 * la commune ou du point de recherche fourni.
 * * le champ `distance` est :
 * * rempli pour les services (non exclusivement) en présentiel.
 * * laissé vide pour les services à distance et par défaut si le mode d'accueil
 * n'est pas définie.
 * * les résultats sont triés par distance croissante.
 *
 * @deprecated
 */
export const searchServicesEndpointApiV0SearchServicesGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    SearchServicesEndpointApiV0SearchServicesGetData,
    ThrowOnError
  >,
) =>
  (options?.client ?? client).get<
    SearchServicesEndpointApiV0SearchServicesGetResponses,
    SearchServicesEndpointApiV0SearchServicesGetErrors,
    ThrowOnError
  >({ url: "/api/v0/search/services", ...options });

/**
 * Récupérer le référentiel des frais
 *
 * @deprecated
 */
export const asDictListApiV0DocFraisGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AsDictListApiV0DocFraisGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    AsDictListApiV0DocFraisGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/v0/doc/frais", ...options });

/**
 * Récupérer le référentiel des labels nationaux
 *
 * @deprecated
 */
export const asDictListApiV0DocLabelsNationauxGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AsDictListApiV0DocLabelsNationauxGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    AsDictListApiV0DocLabelsNationauxGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/v0/doc/labels-nationaux", ...options });

/**
 * Récupérer le référentiel des modes d'accueil
 *
 * @deprecated
 */
export const asDictListApiV0DocModesAccueilGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AsDictListApiV0DocModesAccueilGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    AsDictListApiV0DocModesAccueilGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/v0/doc/modes-accueil", ...options });

/**
 * Récupérer le référentiel des modes d'orientation de l'accompagnateur
 *
 * @deprecated
 */
export const asDictListApiV0DocModesOrientationAccompagnateurGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    AsDictListApiV0DocModesOrientationAccompagnateurGetData,
    ThrowOnError
  >,
) =>
  (options?.client ?? client).get<
    AsDictListApiV0DocModesOrientationAccompagnateurGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/v0/doc/modes-orientation-accompagnateur", ...options });

/**
 * Récupérer le référentiel des modes d'orientation du bénéficiaire
 *
 * @deprecated
 */
export const asDictListApiV0DocModesOrientationBeneficiaireGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    AsDictListApiV0DocModesOrientationBeneficiaireGetData,
    ThrowOnError
  >,
) =>
  (options?.client ?? client).get<
    AsDictListApiV0DocModesOrientationBeneficiaireGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/v0/doc/modes-orientation-beneficiaire", ...options });

/**
 * Récupérer le référentiel des profils de publics
 *
 * @deprecated
 */
export const asDictListApiV0DocProfilsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AsDictListApiV0DocProfilsGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    AsDictListApiV0DocProfilsGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/v0/doc/profils", ...options });

/**
 * Récupérer le référentiel des thématiques
 *
 * @deprecated
 */
export const asDictListApiV0DocThematiquesGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AsDictListApiV0DocThematiquesGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    AsDictListApiV0DocThematiquesGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/v0/doc/thematiques", ...options });

/**
 * Récupérer le référentiel des typologies de services
 *
 * @deprecated
 */
export const asDictListApiV0DocTypologiesServicesGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AsDictListApiV0DocTypologiesServicesGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    AsDictListApiV0DocTypologiesServicesGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/v0/doc/typologies-services", ...options });

/**
 * Récupérer le référentiel des typologies de structures
 *
 * @deprecated
 */
export const asDictListApiV0DocTypologiesStructuresGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    AsDictListApiV0DocTypologiesStructuresGetData,
    ThrowOnError
  >,
) =>
  (options?.client ?? client).get<
    AsDictListApiV0DocTypologiesStructuresGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/v0/doc/typologies-structures", ...options });
