// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AsDictListApiV1DocFraisGetData, AsDictListApiV1DocFraisGetResponses, AsDictListApiV1DocModesAccueilGetData, AsDictListApiV1DocModesAccueilGetResponses, AsDictListApiV1DocModesMobilisationGetData, AsDictListApiV1DocModesMobilisationGetResponses, AsDictListApiV1DocPersonnesMobilisatricesGetData, AsDictListApiV1DocPersonnesMobilisatricesGetResponses, AsDictListApiV1DocPublicsGetData, AsDictListApiV1DocPublicsGetResponses, AsDictListApiV1DocReseauxPorteursGetData, AsDictListApiV1DocReseauxPorteursGetResponses, AsDictListApiV1DocThematiquesGetData, AsDictListApiV1DocThematiquesGetResponses, AsDictListApiV1DocTypesServicesGetData, AsDictListApiV1DocTypesServicesGetResponses, ListServicesEndpointApiV1ServicesGetData, ListServicesEndpointApiV1ServicesGetErrors, ListServicesEndpointApiV1ServicesGetResponses, ListSourcesEndpointApiV1SourcesGetData, ListSourcesEndpointApiV1SourcesGetResponses, ListStructuresEndpointApiV1StructuresGetData, ListStructuresEndpointApiV1StructuresGetErrors, ListStructuresEndpointApiV1StructuresGetResponses, RetrieveServiceEndpointApiV1ServicesIdGetData, RetrieveServiceEndpointApiV1ServicesIdGetErrors, RetrieveServiceEndpointApiV1ServicesIdGetResponses, RetrieveStructureEndpointApiV1StructuresIdGetData, RetrieveStructureEndpointApiV1StructuresIdGetErrors, RetrieveStructureEndpointApiV1StructuresIdGetResponses, SearchServicesEndpointApiV1SearchServicesGetData, SearchServicesEndpointApiV1SearchServicesGetErrors, SearchServicesEndpointApiV1SearchServicesGetResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Lister les structures consolidées
 */
export const listStructuresEndpointApiV1StructuresGet = <ThrowOnError extends boolean = false>(options?: Options<ListStructuresEndpointApiV1StructuresGetData, ThrowOnError>) => (options?.client ?? client).get<ListStructuresEndpointApiV1StructuresGetResponses, ListStructuresEndpointApiV1StructuresGetErrors, ThrowOnError>({ url: '/api/v1/structures', ...options });

/**
 * Détailler une structure
 */
export const retrieveStructureEndpointApiV1StructuresIdGet = <ThrowOnError extends boolean = false>(options: Options<RetrieveStructureEndpointApiV1StructuresIdGetData, ThrowOnError>) => (options.client ?? client).get<RetrieveStructureEndpointApiV1StructuresIdGetResponses, RetrieveStructureEndpointApiV1StructuresIdGetErrors, ThrowOnError>({ url: '/api/v1/structures/{id}', ...options });

/**
 * Lister les sources consolidées
 */
export const listSourcesEndpointApiV1SourcesGet = <ThrowOnError extends boolean = false>(options?: Options<ListSourcesEndpointApiV1SourcesGetData, ThrowOnError>) => (options?.client ?? client).get<ListSourcesEndpointApiV1SourcesGetResponses, unknown, ThrowOnError>({ url: '/api/v1/sources', ...options });

/**
 * Lister les services consolidés
 */
export const listServicesEndpointApiV1ServicesGet = <ThrowOnError extends boolean = false>(options?: Options<ListServicesEndpointApiV1ServicesGetData, ThrowOnError>) => (options?.client ?? client).get<ListServicesEndpointApiV1ServicesGetResponses, ListServicesEndpointApiV1ServicesGetErrors, ThrowOnError>({ url: '/api/v1/services', ...options });

/**
 * Détailler un service
 */
export const retrieveServiceEndpointApiV1ServicesIdGet = <ThrowOnError extends boolean = false>(options: Options<RetrieveServiceEndpointApiV1ServicesIdGetData, ThrowOnError>) => (options.client ?? client).get<RetrieveServiceEndpointApiV1ServicesIdGetResponses, RetrieveServiceEndpointApiV1ServicesIdGetErrors, ThrowOnError>({ url: '/api/v1/services/{id}', ...options });

/**
 * Rechercher des services
 *
 * ## Rechercher des services
 *
 * La recherche de services permet de trouver des services dans une commune et à
 * proximité.
 *
 * Les services peuvent être filtrés selon par thématiques, frais, typologies et
 * code_insee de commune.
 *
 * En particulier, lorsqu'un `code_commune` est fourni :
 *
 * * les services sont filtrés par zone de diffusion lorsque celle-ci est définie.
 * * de plus, les services en présentiel sont filtrés dans un rayon de 50km autour de
 * la commune ou du point de recherche fourni.
 * * le champ `distance` est :
 * * rempli pour les services (non exclusivement) en présentiel.
 * * laissé vide pour les services à distance et par défaut si le mode d'accueil
 * n'est pas définie.
 * * les résultats sont triés par distance croissante.
 */
export const searchServicesEndpointApiV1SearchServicesGet = <ThrowOnError extends boolean = false>(options?: Options<SearchServicesEndpointApiV1SearchServicesGetData, ThrowOnError>) => (options?.client ?? client).get<SearchServicesEndpointApiV1SearchServicesGetResponses, SearchServicesEndpointApiV1SearchServicesGetErrors, ThrowOnError>({ url: '/api/v1/search/services', ...options });

/**
 * Récupérer le référentiel des frais
 */
export const asDictListApiV1DocFraisGet = <ThrowOnError extends boolean = false>(options?: Options<AsDictListApiV1DocFraisGetData, ThrowOnError>) => (options?.client ?? client).get<AsDictListApiV1DocFraisGetResponses, unknown, ThrowOnError>({ url: '/api/v1/doc/frais', ...options });

/**
 * Récupérer le référentiel des modes d'accueil
 */
export const asDictListApiV1DocModesAccueilGet = <ThrowOnError extends boolean = false>(options?: Options<AsDictListApiV1DocModesAccueilGetData, ThrowOnError>) => (options?.client ?? client).get<AsDictListApiV1DocModesAccueilGetResponses, unknown, ThrowOnError>({ url: '/api/v1/doc/modes-accueil', ...options });

/**
 * Récupérer le référentiel des modes de mobilisation
 */
export const asDictListApiV1DocModesMobilisationGet = <ThrowOnError extends boolean = false>(options?: Options<AsDictListApiV1DocModesMobilisationGetData, ThrowOnError>) => (options?.client ?? client).get<AsDictListApiV1DocModesMobilisationGetResponses, unknown, ThrowOnError>({ url: '/api/v1/doc/modes-mobilisation', ...options });

/**
 * Récupérer le référentiel des personnes mobilisatrices
 */
export const asDictListApiV1DocPersonnesMobilisatricesGet = <ThrowOnError extends boolean = false>(options?: Options<AsDictListApiV1DocPersonnesMobilisatricesGetData, ThrowOnError>) => (options?.client ?? client).get<AsDictListApiV1DocPersonnesMobilisatricesGetResponses, unknown, ThrowOnError>({ url: '/api/v1/doc/personnes-mobilisatrices', ...options });

/**
 * Récupérer le référentiel des publics
 */
export const asDictListApiV1DocPublicsGet = <ThrowOnError extends boolean = false>(options?: Options<AsDictListApiV1DocPublicsGetData, ThrowOnError>) => (options?.client ?? client).get<AsDictListApiV1DocPublicsGetResponses, unknown, ThrowOnError>({ url: '/api/v1/doc/publics', ...options });

/**
 * Récupérer le référentiel des réseaux porteurs
 */
export const asDictListApiV1DocReseauxPorteursGet = <ThrowOnError extends boolean = false>(options?: Options<AsDictListApiV1DocReseauxPorteursGetData, ThrowOnError>) => (options?.client ?? client).get<AsDictListApiV1DocReseauxPorteursGetResponses, unknown, ThrowOnError>({ url: '/api/v1/doc/reseaux-porteurs', ...options });

/**
 * Récupérer le référentiel des thématiques
 */
export const asDictListApiV1DocThematiquesGet = <ThrowOnError extends boolean = false>(options?: Options<AsDictListApiV1DocThematiquesGetData, ThrowOnError>) => (options?.client ?? client).get<AsDictListApiV1DocThematiquesGetResponses, unknown, ThrowOnError>({ url: '/api/v1/doc/thematiques', ...options });

/**
 * Récupérer le référentiel des types de services
 */
export const asDictListApiV1DocTypesServicesGet = <ThrowOnError extends boolean = false>(options?: Options<AsDictListApiV1DocTypesServicesGetData, ThrowOnError>) => (options?.client ?? client).get<AsDictListApiV1DocTypesServicesGetResponses, unknown, ThrowOnError>({ url: '/api/v1/doc/types-services', ...options });
