// This file is generated by Velite

import type __vc from '../velite.config.ts'

type Collections = typeof __vc.collections

export type Formation = Collections['formations']['schema']['_output']
export declare const formations: Formation[]
