
  create table "public"."ingestion_records" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone,
    "source_id" text not null,
    "source_created_at" timestamp with time zone not null,
    "source_updated_at" timestamp with time zone not null,
    "source_raw" text not null,
    "markdown" text not null,
    "metadata" jsonb not null,
    "is_current_version" boolean not null default true
      );


alter table "public"."ingestion_records" enable row level security;


  create table "public"."ingestion_reports" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "record_id" uuid not null,
    "report_type" text not null,
    "markdown" text not null,
    "metadata" jsonb not null
      );


alter table "public"."ingestion_reports" enable row level security;

CREATE UNIQUE INDEX ingestion_raw_records_pkey ON public.ingestion_records USING btree (id);

CREATE UNIQUE INDEX ingestion_raw_records_source_id_key ON public.ingestion_records USING btree (source_id);

CREATE UNIQUE INDEX ingestion_reports_pkey ON public.ingestion_reports USING btree (id);

CREATE INDEX ingestion_raw_records_updated_at_idx ON public.ingestion_records USING btree (updated_at);

CREATE INDEX ingestion_raw_records_source_updated_at_idx ON public.ingestion_records USING btree (source_updated_at);

CREATE INDEX ingestion_reports_record_id_idx ON public.ingestion_reports USING btree (record_id);

CREATE INDEX ingestion_reports_report_type_idx ON public.ingestion_reports USING btree (report_type);

CREATE INDEX ingestion_raw_records_metadata_idx ON public.ingestion_records USING gin (metadata);

CREATE INDEX ingestion_reports_metadata_idx ON public.ingestion_reports USING gin (metadata);

comment on column public.ingestion_records.markdown is 'Contains the complete markdown file including frontmatter.';
comment on column public.ingestion_records.metadata is 'Contains the JSONB representation of the frontmatter for indexing.';
comment on column public.ingestion_reports.markdown is 'Contains the complete markdown file including frontmatter.';
comment on column public.ingestion_reports.metadata is 'Contains the JSONB representation of the frontmatter for indexing.';

alter table "public"."ingestion_records" add constraint "ingestion_raw_records_pkey" PRIMARY KEY using index "ingestion_raw_records_pkey";

alter table "public"."ingestion_reports" add constraint "ingestion_reports_pkey" PRIMARY KEY using index "ingestion_reports_pkey";

alter table "public"."ingestion_records" add constraint "ingestion_raw_records_source_id_key" UNIQUE using index "ingestion_raw_records_source_id_key";

alter table "public"."ingestion_reports" add constraint "ingestion_reports_record_id_fkey" FOREIGN KEY (record_id) REFERENCES public.ingestion_records(id) ON DELETE CASCADE not valid;

alter table "public"."ingestion_reports" validate constraint "ingestion_reports_record_id_fkey";

grant delete on table "public"."ingestion_records" to "anon";

grant insert on table "public"."ingestion_records" to "anon";

grant references on table "public"."ingestion_records" to "anon";

grant select on table "public"."ingestion_records" to "anon";

grant trigger on table "public"."ingestion_records" to "anon";

grant truncate on table "public"."ingestion_records" to "anon";

grant update on table "public"."ingestion_records" to "anon";

grant delete on table "public"."ingestion_records" to "authenticated";

grant insert on table "public"."ingestion_records" to "authenticated";

grant references on table "public"."ingestion_records" to "authenticated";

grant select on table "public"."ingestion_records" to "authenticated";

grant trigger on table "public"."ingestion_records" to "authenticated";

grant truncate on table "public"."ingestion_records" to "authenticated";

grant update on table "public"."ingestion_records" to "authenticated";

grant delete on table "public"."ingestion_records" to "postgres";

grant insert on table "public"."ingestion_records" to "postgres";

grant references on table "public"."ingestion_records" to "postgres";

grant select on table "public"."ingestion_records" to "postgres";

grant trigger on table "public"."ingestion_records" to "postgres";

grant truncate on table "public"."ingestion_records" to "postgres";

grant update on table "public"."ingestion_records" to "postgres";

grant delete on table "public"."ingestion_records" to "service_role";

grant insert on table "public"."ingestion_records" to "service_role";

grant references on table "public"."ingestion_records" to "service_role";

grant select on table "public"."ingestion_records" to "service_role";

grant trigger on table "public"."ingestion_records" to "service_role";

grant truncate on table "public"."ingestion_records" to "service_role";

grant update on table "public"."ingestion_records" to "service_role";

grant delete on table "public"."ingestion_reports" to "anon";

grant insert on table "public"."ingestion_reports" to "anon";

grant references on table "public"."ingestion_reports" to "anon";

grant select on table "public"."ingestion_reports" to "anon";

grant trigger on table "public"."ingestion_reports" to "anon";

grant truncate on table "public"."ingestion_reports" to "anon";

grant update on table "public"."ingestion_reports" to "anon";

grant delete on table "public"."ingestion_reports" to "authenticated";

grant insert on table "public"."ingestion_reports" to "authenticated";

grant references on table "public"."ingestion_reports" to "authenticated";

grant select on table "public"."ingestion_reports" to "authenticated";

grant trigger on table "public"."ingestion_reports" to "authenticated";

grant truncate on table "public"."ingestion_reports" to "authenticated";

grant update on table "public"."ingestion_reports" to "authenticated";

grant delete on table "public"."ingestion_reports" to "postgres";

grant insert on table "public"."ingestion_reports" to "postgres";

grant references on table "public"."ingestion_reports" to "postgres";

grant select on table "public"."ingestion_reports" to "postgres";

grant trigger on table "public"."ingestion_reports" to "postgres";

grant truncate on table "public"."ingestion_reports" to "postgres";

grant update on table "public"."ingestion_reports" to "postgres";

grant delete on table "public"."ingestion_reports" to "service_role";

grant insert on table "public"."ingestion_reports" to "service_role";

grant references on table "public"."ingestion_reports" to "service_role";

grant select on table "public"."ingestion_reports" to "service_role";

grant trigger on table "public"."ingestion_reports" to "service_role";

grant truncate on table "public"."ingestion_reports" to "service_role";

grant update on table "public"."ingestion_reports" to "service_role";
