
  create table "public"."di_structures" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp without time zone not null default now(),
    "raw_data" text not null,
    "data" jsonb
      );


alter table "public"."di_structures" enable row level security;

CREATE UNIQUE INDEX di_structures_pkey ON public.di_structures USING btree (id);

alter table "public"."di_structures" add constraint "di_structures_pkey" PRIMARY KEY using index "di_structures_pkey";

grant delete on table "public"."di_structures" to "anon";

grant insert on table "public"."di_structures" to "anon";

grant references on table "public"."di_structures" to "anon";

grant select on table "public"."di_structures" to "anon";

grant trigger on table "public"."di_structures" to "anon";

grant truncate on table "public"."di_structures" to "anon";

grant update on table "public"."di_structures" to "anon";

grant delete on table "public"."di_structures" to "authenticated";

grant insert on table "public"."di_structures" to "authenticated";

grant references on table "public"."di_structures" to "authenticated";

grant select on table "public"."di_structures" to "authenticated";

grant trigger on table "public"."di_structures" to "authenticated";

grant truncate on table "public"."di_structures" to "authenticated";

grant update on table "public"."di_structures" to "authenticated";

grant delete on table "public"."di_structures" to "postgres";

grant insert on table "public"."di_structures" to "postgres";

grant references on table "public"."di_structures" to "postgres";

grant select on table "public"."di_structures" to "postgres";

grant trigger on table "public"."di_structures" to "postgres";

grant truncate on table "public"."di_structures" to "postgres";

grant update on table "public"."di_structures" to "postgres";

grant delete on table "public"."di_structures" to "service_role";

grant insert on table "public"."di_structures" to "service_role";

grant references on table "public"."di_structures" to "service_role";

grant select on table "public"."di_structures" to "service_role";

grant trigger on table "public"."di_structures" to "service_role";

grant truncate on table "public"."di_structures" to "service_role";

grant update on table "public"."di_structures" to "service_role";


