-- Enable Supabase Realtime for letta_reports
-- Required for the MetadataView component to receive INSERT events
-- when metadata reports are generated by the AI agent.

alter publication supabase_realtime add table letta_reports;
