
  create table "public"."di_services" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp without time zone not null default now(),
    "raw_data" text not null,
    "data" jsonb
      );


alter table "public"."di_services" enable row level security;

CREATE UNIQUE INDEX di_services_pkey ON public.di_services USING btree (id);

alter table "public"."di_services" add constraint "di_services_pkey" PRIMARY KEY using index "di_services_pkey";

-- GIN index for efficient JSONB containment queries (@>, ?, ?&, ?|)
CREATE INDEX di_services_data_gin_idx ON public.di_services USING gin (data jsonb_path_ops);

-- B-tree indexes on commonly queried JSONB fields
CREATE INDEX di_services_data_id_idx ON public.di_services USING btree ((data->>'id'));
CREATE INDEX di_services_data_source_idx ON public.di_services USING btree ((data->>'source'));
CREATE INDEX di_services_data_structure_id_idx ON public.di_services USING btree ((data->>'structure_id'));
CREATE INDEX di_services_data_type_idx ON public.di_services USING btree ((data->>'type'));
CREATE INDEX di_services_data_commune_idx ON public.di_services USING btree ((data->>'commune'));
CREATE INDEX di_services_data_code_postal_idx ON public.di_services USING btree ((data->>'code_postal'));
CREATE INDEX di_services_data_date_maj_idx ON public.di_services USING btree ((data->>'date_maj'));

-- Grant read-only access to authenticated users (for frontend)
grant select on table "public"."di_services" to "authenticated";

grant delete on table "public"."di_services" to "postgres";

grant insert on table "public"."di_services" to "postgres";

grant references on table "public"."di_services" to "postgres";

grant select on table "public"."di_services" to "postgres";

grant trigger on table "public"."di_services" to "postgres";

grant truncate on table "public"."di_services" to "postgres";

grant update on table "public"."di_services" to "postgres";

grant delete on table "public"."di_services" to "service_role";

grant insert on table "public"."di_services" to "service_role";

grant references on table "public"."di_services" to "service_role";

grant select on table "public"."di_services" to "service_role";

grant trigger on table "public"."di_services" to "service_role";

grant truncate on table "public"."di_services" to "service_role";

grant update on table "public"."di_services" to "service_role";

